## Import numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)   #Checking Numpy Version

1.19.2


In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


## Dimensions in Arrays

0-D  Array

In [6]:
arr = np.array(42)
print(arr)

42


1-D Array

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2-D Array

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


 define the number of dimensions by  ndmin

In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Access Array Elements

In [10]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
print(a[0] + a[3])

5


In [12]:
print(b[0,2])

3


In [13]:
# Negative Indexing
print(a[-2])
print(b[-1,-2])

4
5


## Slicing arrays

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [15]:
print(arr[1:5])

[2 3 4 5]


In [16]:
print(arr[1:])

[2 3 4 5 6 7]


In [17]:
print(arr[:4]) #not include Index 4

[1 2 3 4]


In [18]:
print(arr[1:5:2])    #Skip two value from 1 to 5

[2 4]


In [19]:
print(arr[::3]) #Skip 3 value 

[1 4 7]


## 2-D Array

In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 0:4])

[6 7 8 9]


In [21]:
print(arr[0:3, 3]) #From both elements, return index 3

[4 9]


In [22]:
print(arr[0:2, 1:4]) #From both elements, slice index 1 to index 4 (not included),

[[2 3 4]
 [7 8 9]]


## Datatype of array

In [23]:
a.dtype

dtype('int32')

In [24]:
b.dtype

dtype('int32')

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

In [27]:
arr = np.array([1, 2, 3, 4], dtype='S')  #S fro String

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [28]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')  #Change datatype from float to int

In [29]:
print(arr)
arr.dtype

[1.1 2.1 3.1]


dtype('float64')

In [30]:
print(newarr)
newarr.dtype

[1 2 3]


dtype('int32')

## Copy & View

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
#copy
x = arr.copy()                #Not affect the original array
arr[0]=42

In [33]:
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [34]:
#View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()                                  #Change the Original array
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[42  2  3  4  5]


## Shape of array

In [36]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [37]:
arr.shape

(1, 1, 1, 1, 4)

In [38]:
a = np.array([[1,2,3,4,5]])

In [39]:
a.shape

(1, 5)

In [40]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [41]:
arr.shape   #(row,column)

(2, 4)

In [42]:
#reshape
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
arr.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Join Array

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [45]:
arr = np.concatenate((arr1, arr2))

In [46]:
print(arr)

[1 2 3 4 5 6]


In [47]:
arr = np.stack((arr1, arr2), axis=1)

In [48]:
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
arr = np.hstack((arr1, arr2))  #Stacking Along Rows  hstack function
print(arr)

[1 2 3 4 5 6]


In [50]:
arr = np.vstack((arr1, arr2))  #Stacking Along columns  vstack function
print(arr)

[[1 2 3]
 [4 5 6]]


## Split Array

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)

In [52]:
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [53]:
print(newarr[3])

[6]


## Search

In [54]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(arr==4))

(array([3, 5, 6], dtype=int64),)


In [55]:
#Sort
np.sort(arr)

array([1, 2, 3, 4, 4, 4, 5])